default:	all
.PHONY: clean all mrproper
#include $(ROOT)/Makefile_templates/*_rule/Makefile
#include *_rule/Makefile
include $(HOME)/Makefile_templates/*_rule/Makefile

# Original files
FIGs := $(wildcard *.fig)
TEXs := $(wildcard *.tex)
GPTs := $(wildcard *.gpt)
Ms   := $(wildcard *.m)

# Temporal files
DATs += $(Ms:%.m=%.dat)
TMPs += $(DATs)

EPSs += $(FIGs:%.fig=%.eps)
EPSs += $(TEXs:%.tex=%.eps)
EPSs += $(GPTs:%.gpt=%.eps)
TMPs += $(EPSs)

#SVGs += $(FIGs:%.fig=%.svg)	# .svg files generated by .fig files
#SVGs += $(TEXs:%.tex=%.svg)     # .svg files generated by .tex files
#TMPs += $(SVGs)

#TMPs += $(FIGs:%.fig=%.pdf)
TFIGs += $(GPTs:%.gpt=%.fig)    # .fig files generated by .gpt files
TMPs += $(TFIGs)
#PNGs += $(SVGs:%.svg=%.png)
#TMPs += $(PNGs)


# Target (definitive) files
#TARs += $(FIGs:%.fig=%.png)
#TARs += $(TFIGs:%.fig=%.png)
#TARs += $(TEXs:%.tex=%.png)

PNGs += $(EPSs:%.eps=%.png)
TARs += $(PNGs)

all:	$(TMPs) $(TARs)

clean:
	rm -f $(TMPs) *.log *.aux

mrproper:
	rm -f $(TMPs) $(TARs)

info:
	@echo Original files: $(FIGs) $(TEXs) $(GPTs)
	@echo Temporal files: $(TMPs)
	@echo Target files: $(TARs)

